# Resolucion Ejercicio 2

## 5to año - Ingeniería en Sistemas de Información

### Facultad Regional Villa María

### Enunciado

Realizar una práctica básica con numpy: dadas las matrices

A = \begin{bmatrix}
        1 & 2 & 3 \\
        4 & 5 & 6
    \end{bmatrix}

B = \begin{bmatrix}
        -1 & 0 \\
        1 & 1 \\
        0 & 1
    \end{bmatrix}

* Construir las matrices en numpy
* Hacer con dichas matrices $A-B^T$ e imprimir su resultado.
* Hacer con dichas matrices $(A.B)^{-1}$ e imprimir su resultado.

Recomendación: Usar un notebook de jupyter para hacer los ejercicios.




### Resolución


In [1]:
#Creacion de la matriz A
import numpy as np 
A= np.array([[1,2,3],[4,5,6]])
print(A)

[[1 2 3]
 [4 5 6]]


In [2]:
#Creacion de la matriz B
B= np.array([[-1,0],[1,1],[0,1]])
print(B)

[[-1  0]
 [ 1  1]
 [ 0  1]]


In [3]:
#Transpuesta de la matriz B
C=np.transpose(B)
C

array([[-1,  1,  0],
       [ 0,  1,  1]])

In [4]:
#Resta de la matriz A con B transpuesta
D= A-C
print(D)

[[2 1 3]
 [4 4 5]]


In [5]:
#Multiplicacion de A y B
E=A.dot(B)
E

array([[ 1,  5],
       [ 1, 11]])

In [6]:
#Inversa de la multiplicacion de A y B
F= np.linalg.inv(E)
print(F)

[[ 1.83333333 -0.83333333]
 [-0.16666667  0.16666667]]
